import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/footer/Footer';
import Navbar from '@/components/navbar/NavBar';
import Aside from '@/components/aside/Aside';
import Links from '@/components/links/Links';
import Menu from '@/components/menu/Menu';
import MyInf from '@/components/myInf/MyInf';
import { AntdRegistry } from '@ant-design/nextjs-registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} relative flex justify-center min-h-screen h-full bg-[#E0E9E2]`}>
                <AntdRegistry>
                    <Aside className="sticky top-0 z-50 h-screen">
                        <MyInf></MyInf>
                        <Links></Links>
                    </Aside>
                    <div className="flex flex-col h-full">
                        <Navbar className="sticky w-[1280px] top-0 z-50 max-2xl:w-[1080px]"></Navbar>
                        <main className="top-14 flex flex-1 min-h-[calc(100vh-56px)] min-w-[768px] max-w-[1280px] w-full max-2xl:w-[1080px]">
                            <div className="flex flex-col flex-1 bg-[#f5f9f6] w-full px-6 pt-6">
                                {children}
                                <Footer></Footer>
                            </div>
                            <Aside className="max-xl:hidden">
                                <Menu></Menu>
                            </Aside>
                        </main>
                    </div>
                </AntdRegistry>
            </body>
        </html>
    );
}
