import {
    ClockCircleOutlined,
    CopyrightOutlined,
    HomeOutlined,
    LikeOutlined,
    PayCircleOutlined,
    UserOutlined,
} from '@ant-design/icons';
import { Breadcrumb } from 'antd';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import  Comment from '@/components/comment/Comment';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${inter.className} flex flex-col gap-4 h-full`}>
            <Breadcrumb
                className={twMerge('bg-white rounded-lg', '[&.ant-breadcrumb]:py-2 [&.ant-breadcrumb]:px-3')}
                items={[
                    {
                        href: '',
                        title: <HomeOutlined />,
                    },
                    {
                        href: '',
                        title: (
                            <>
                                <UserOutlined />
                                <span>Application List</span>
                            </>
                        ),
                    },
                    {
                        title: 'Application',
                    },
                ]}
            />
            <div className="bg-white rounded-lg p-6">
                {children}
                <li className="flex justify-between text-xs py-8">
                    <div className="flex gap-1 items-center">
                        <ClockCircleOutlined />
                        <span>最后更新时间: mock</span>
                    </div>
                    <div className="flex gap-1 items-center">
                        <CopyrightOutlined />
                        <span>允许规范转载</span>
                    </div>
                </li>
                {/* todo:按钮颜色处理一下 */}
                <div className="flex justify-center items-center gap-12 w-full text-sm">
                    <button className="flex items-center gap-1 py-1 px-2 rounded-xl text-white bg-gradient-to-tr from-[rgba(203,158,73,1)] to-[rgba(255,225,128,1)]">
                        <PayCircleOutlined className=" text-red" />
                        打赏
                    </button>
                    <button className="flex items-center gap-1 py-1 px-2 rounded-xl text-white bg-gradient-to-tr from-[rgba(243,113,113,1)] to-[rgba(255,168,168,1)]">
                        <LikeOutlined />
                        点赞
                    </button>
                </div>
            </div>
            <span>评论</span>
            <Comment></Comment>
        </div>
    );
}
